config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  delete "/admin/merchant/:id" => 'admin/merchant#destroy', as: :delete_merchant
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  root to: "dashboards#index"

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    get :my_orders, on: :collection
    get :deliver_order, :on => :member
    get :order_status, :on => :member
  end
  match "make_order", to: "orders#make_order", as: :make_order, via: [:get, :post]

  match '/send_mail', to: 'pages#send_mail', via: 'post'

  resources :dashboards do
    post :import, :on => :collection
    get :upload_inventory, :on => :collection
  end

  resources :items

  resources :pages do
    get :about_us, :on => :collection
    get :faqs, :on => :collection
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :item
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!
	require 'csv'

	def index
		session.delete(:items_id) if session[:items_id].present? 
		session.delete(:postal_code) if session[:postal_code].present?
		session.delete(:delivery_add) if session[:delivery_add].present?
		session.delete(:delivery_date) if session[:delivery_date].present?
		session.delete(:item) if session[:item].present?

		@sample_csv = ["code", "item", "qty"]
	    respond_to do |format|
	      format.html
	      format.csv { send_data @sample_csv.to_csv}
	    end
	end

	def user_order
		session[:items_id] = [] if !session[:items_id].present?
		session[:item] = {}
		id = params[:id]
		m = id.match /(.+)-(\d+)/
		item = Item.find(m[1]).code
		session[:item].merge!(value: m[1])
		session[:item].merge!(key: m[2])
		session[:items_id] = session[:items_id].reject { |h| h["key"] == m[2] } 
		session[:items_id] << session[:item]

		# puts session[:items_id].inspect
		render :nothing => true
	end

	def show_order
		@start_date = Date.today
		@b, @c = [], []
		session[:items_id].each do |a|
			id = a["value"].match /(.+)-(\d+)/
			@b << id[1]
			@c << id[2]
		end
		@items = Item.where("id IN (?)", @b)
	end


	def modify_order
		@start_date = Date.today
		@end_date = session[:delivery_date].to_date
		@b, @c, @short_items = [], [], []
		session[:items_id].each do |a|
			id = a["value"].match /(.+)-(\d+)/
			item_code = Item.find(id[1])

			@c << id[2]

			@items = Item.where("code =? and name =? and stock >=?", item_code.code, item_code.name, id[2]).limit(3)

      		@short = @items.sort_by {|x| [x.price, x.delivery_days] }
      		@short_items << @short
		end
		@i = session[:items_id]
	end

	def upload
		session[:delivery_add] = params[:delivery_add]
		session[:postal_code] = params[:postal_code]
		session[:delivery_date] = params[:delivery_date]
		@start_date = Date.today
		@end_date = params[:delivery_date].to_date
		csv_text = File.read(params[:file].path)
	    if !csv_text.blank?
	    	csv = CSV.parse(csv_text, :headers => true)
	    	@short_items = []
	    	@qty = []
	        csv.each do |row|
	        	@items = Item.where("code =? and name =? and stock >=?", row["code"], row["item"], row["qty"]).limit(3)
	        	@qty << row["qty"]
	      		@short = @items.sort_by {|x| [x.price, x.delivery_days] }
	      		@short_items << @short
	      	end
		end
	end

	def make_order
		@delivery_address = session[:delivery_add]
		if session[:items_id].present?
			session[:recent_orders] = []
			session[:items_id].each do |a|
				id = a["value"].match /(.+)-(\d+)/
				item = Item.find(id[1])

				delivery_date =  Date.today + item.delivery_days
				order = Order.create!(user_id: current_user.id, merchant_id: item.user_id, item_id: item.id, item_qty: id[2], delivery_add: session[:delivery_add], postal_code: session[:postal_code], delivery_date: delivery_date, is_confirm: true )
				session[:recent_orders] << order.id

				@stock = item.update_attributes(stock: item.stock.to_i - id[2].to_i)

			end
			NotificationMailer.purchase_notification(session[:recent_orders], current_user.email).deliver_now
			session.delete(:items_id)
			session.delete(:postal_code)
			session.delete(:delivery_add)
			session.delete(:delivery_date)
			session.delete(:count)
			session.delete(:item)
			@my_orders = Order.where("id IN (?)", session[:recent_orders])
			flash[:message] = "Order placed successfully!"		
		else
			@my_orders = Order.where("id IN (?)", session[:recent_orders])
		end
	end

	def my_orders
		@my_orders = Order.where("merchant_id =?", current_user.id)
	end

	def deliver_order
		@order = Order.find_by("id =?", params[:id])
		@user_email = @order.user.email
		if @order.is_delivered == true and @order.status == true
			@updated_order = @order.update_attributes(is_delivered: false, status: false)
		else
			@updated_order = @order.update_attributes(is_delivered: true, status: true)
			NotificationMailer.order_deliver_notification(@order, @user_email).deliver_now
		end
		render :nothing => true
	end

	def order_status
		@user_order = Order.find_by("id =?", params[:id])
		if @user_order.is_completed == true
			@update_order = @user_order.update_attributes(is_completed: false)
		else
			NotificationMailer.transaction_complete_notification(@user_order).deliver_now
			@update_order = @user_order.update_attributes(is_completed: true, confirm_date: DateTime.now)
		end
		render :nothing => true
	end

	def show
		@user_order = Order.find(params[:id])
	end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_user_dashbord.html.erb
<div class="container">
	<div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
			<h3 class="star-heading">
				New Order
			</h3>
        </div>
    </div>
	<div class="row">
		<div class="col-xs-12 col-lg-6 col-sm-12 col-md-6">
			<%= form_tag  upload_orders_path, multipart: true, onsubmit: "return Validate(this);" do %>
				<div class="user_order tab-pane1">
					<div class="form-group">
						<p>Delivery address</p>
						<%= text_area_tag :delivery_add, "", class: "form-control" %>
					</div>
					<div class="form-group">
						<p>Postal code</p>
						<%= text_field_tag :postal_code, "", class: "form-control" %>
					</div>
					<div class="form-group">
						<p>Delivery date</p>
						<%= text_field_tag :delivery_date, "", id: 'datepicker', class: "form-control" %>
					</div>
					<div class="nxt-btn">
						<a class="btn btn-primary btnNext pull-right" >Next</a>
					</div>
				</div>
				<div class="user_order tab-pane2">
					<h4 class="search-text">Search</h4>
					<div class="form-group search-csv">
						<%= file_field_tag :file, :required => true %>

						<%= link_to "Download Sample CSV", orders_path(format: "csv"), class: "smpl-csv" %>
					</div>
					<p class="important-note"><span class="note-bold">Note* </span>User search CSV must has been this fields <span class="note-bold">code</span>, <span class="note-bold">item</span> and <span class="note-bold">qty</span>.</p>
					<div class="nxt-prev">
						<a class="btn btn-primary btnPrevious" >Back</a>

						<%= submit_tag "Search", class: "btn btn-primary pull-right" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
  	$('#datepicker').datepicker({ dateFormat: 'dd-mm-yy' });
	$('.btnNext').click(function(){
      $('.tab-pane1').css('display', 'none');
      $('.tab-pane2').css('display', 'block');
	});
	$('.btnPrevious').click(function(){
      $('.tab-pane1').css('display', 'block');
      $('.tab-pane2').css('display', 'none');
	});
  });
</script>

<style type="text/css">
	.tab-pane2 {
		display: none;
	}

	a.btn.btn-primary.new-order.pull-right {
    	display: none;
	}
</style>

app/views/orders/index.html.erb
<div>
	<%# if current_user.user_type == true %>
        <%#= render :partial => 'merchant_dashbord' %>
	<%# else %>
        <%= render :partial => 'user_dashbord' %>
	<%# end %>
</div>

<script type="text/javascript">
var _validFileExtensions = [".csv"];    
function Validate(oForm) {
    var arrInputs = oForm.getElementsByTagName("input");
    for (var i = 0; i < arrInputs.length; i++) {
        var oInput = arrInputs[i];
        if (oInput.type == "file") {
            var sFileName = oInput.value;
            if (sFileName.length > 0) {
                var blnValid = false;
                for (var j = 0; j < _validFileExtensions.length; j++) {
                    var sCurExtension = _validFileExtensions[j];
                    if (sFileName.substr(sFileName.length - sCurExtension.length, sCurExtension.length).toLowerCase() == sCurExtension.toLowerCase()) {
                        blnValid = true;
                        break;
                    }
                }
                
                if (!blnValid) {
                    alert("Sorry, file is invalid, allowed extensions are: " + _validFileExtensions.join(", "));
                    return false;
                }
            }
        }
    }
  
    return true;
}
</script>

app/views/orders/make_order.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-12 main-class-done">
			<h3 class="star-heading">
            	Done!
          	</h3>
			<div class="row main">
				<div class="col-lg-12">
					<p class="order-date">Date:- <span><%= Date.today %></span></p>
				</div>
			</div>
			<div class="row main">
				<div class="col-lg-12">
					<div class="table-responsive">
			            <table class="table table-striped receipt">
			                <thead>
			                    <tr>
			                        <th>Order No</th>
			                        <th>Delivery Date</th>
			                        <th>Item Name</th>
			                        <th>Item Qty</th>
			                        <th>Item Price</th>
			                        <th>GST</th>
			                        <th>Total</th>
			                    </tr>
			                </thead>

			                <tbody>
			                	<% @total = [] %>
			                	<% @item_total, @gst_total = 0, 0 %>
	                            <% @my_orders.each do |h| %>
		                            <tr>
		                                <td><%= h.id %></td>
		                                <td><%= h.delivery_date.strftime("%d/%m/%Y") %></td>
		                                <td><%= h.item.name %></td>
		                                <td><%= h.item_qty %></td>
		                                <td><%= h.item.price %></td>
		                                <td>
		                                	<%
		                                		@gst = h.item.price.to_f * h.item.gst.to_f / 100.00
		                                		@gst = @gst * h.item_qty
		                                	 %>
		                                	<%= @gst.round(2) %>
		                                </td>
		                                <td> 
		                                	<% 
		                                		@price_total = h.item_qty * h.item.price
		                                		@price_total = @price_total + @gst.round(2) 
		                                	%>
		                                	<%= @price_total.round(2) %>
		                                </td>
		                                <% @total << @price_total  %>
		                                <% @item_total = @item_total + h.item.price %>
		                                <% @gst_total = @gst_total + @gst %>
		                            </tr>
		                    	<% end %>
		                    		<% @final_total = @total.inject(0){|sum,x| sum + x } %>
		                    		<tr style="border:2px solid #000;">
		                    			<td style="font-weight: bold;">Total</td>
		                    			<td>&nbsp;</td>
		                    			<td>&nbsp;</td>
		                    			<td>&nbsp;</td>
		                    			<td><%= @item_total.round(2) %></td>
		                    			<td><%= @gst_total.round(2) %></td>
		                    			<td><%= @final_total.round(2) %></td>
		                    		</tr>
		                    		<tr>
		                    			<td>&nbsp;</td>
		                    			<td>&nbsp;</td>
		                    			<td>&nbsp;</td>
		                    			<td>&nbsp;</td>
		                    			<td style="font-weight: bold;">Item price total</td>
		                    			<td style="font-weight: bold;">GST total</td>
		                    			<td style="font-weight: bold;">Total paid</td>
		                    		</tr>
			                </tbody>
			            </table>
	        		</div>
				</div>
			</div>
			<div class="row main">
				<div class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
					<p class="delivery_address">Delivery address:-</p>
				</div>
				<div class="col-xs-6 col-sm-6 col-md-2 col-lg-2">
					<p class="order-delivery-add"><%= @delivery_address %></p>
				</div>
			</div>
			<div class="row main">
				<!-- <div class="col-lg-6">
					<button type="button" class="btn btn-success">Print</button>
				</div> -->
				<div class="col-lg-12">
					<%= link_to "New order", orders_path, class:"btn btn-primary make-new-order" %>
					<%#= link_to "Dashboard", dashboards_path, class:"btn btn-primary go-dashboard" %>
				</div>
			</div>
		</div>
	</div>
</div>
<style type="text/css">
    a#u-order{
        display: none;
    }

    a.btn.btn-primary.new-order.pull-right {
        display: none;
    }
</style>

app/views/orders/modify_order.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 compare-order">
          <h3 class="star-heading">
            Compare and order
          </h3>
        </div>
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Item Specification</th>
                        <th>Item Price</th>
                        <th>Item Delivery Days</th>
                        <th>Qty</th>
                        <th>Item Delivery Date</th>
                        <th>Make Order</th>
                    </tr>
                </thead>

                <tbody>
                    <% i = 0 %>
                    <% @short_items.each_with_index do |h, index| %>
                        <% h.each do |s| %>
                            <tr id="element" class="item_<%= s.id %>">
                                <td><%= s.code %></td>
                                <td><%= s.name %></td>
                                <td><%= s.specification %></td>
                                <td><%= s.price %></td>
                                <td><%= s.delivery_days %></td>
                                <td><%= @c[i] %></td>
                                <td><%= (@start_date + s.delivery_days).strftime("%d/%m/%Y") %></td>
                                <td>
                                    <% session[:items_id][index] %>
                                    <label><input type="radio" class="user_item" id="item_<%= s.id %>" name="<%= s.code %>" data-id="<%= s.id %>-<%= @c[i]%>-<%= session[:items_id][index]["key"] %>" data-val="<%= @c[i] %>"></label>
                                </td>
                            </tr>
                        <% end %>
                            <tr>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                        <% i += 1 %>
                    <% end %>
                </tbody>
                <div id="result"></div>
            </table>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <%= link_to "Next", show_order_orders_path, class: 'btn btn-primary compare-btn pull-right'%>
        </div>
  </div>
</div>


<% @z = [] %>
<% @l = [] %>
<% @i.each do |m|%>
    <% id = m["value"].match /(.+)-(\d+)/ %>
  <% @z << id[1].to_i %>
  <% @l << id[2].to_i  %>
<% end %>
<% @size = @z.size %>
<%= hidden_field_tag :item_id , @z %>

<script type="text/javascript">

    $(document).ready(function(){
        var a = $("#item_id").val();
        var n = "<%= @l %>";
        var size = "<%= @size %>"
        var res = a.split(" ");
        for(i=0;i<=size-1;i++){
            // alert(a[i])
            $("#item_"+res[i]).prop("checked", true);
            $(".item_"+res[i]).css('background-color', 'rgb(200, 225, 255)');
            // $("#item_10").prop("checked", true);
        }

        $(".user_item").click(function(){
            var dclass = $(this).closest('tr').next('tr').attr("class");
            var pclass = $(this).closest('tr').prev('tr').attr("class");
            var ddclass = $(this).closest('tr').next('tr').next('tr').attr("class");
            var ppclass = $(this).closest('tr').prev('tr').prev('tr').attr("class");
            $('.'+ dclass).css('background-color', 'white');
            $('.'+ pclass).css('background-color', 'white');
            $('.'+ ddclass).css('background-color', 'white');
            $('.'+ ppclass).css('background-color', 'white');
            var a = $(this).attr("id");
            $('.'+ a).css('background-color', 'rgb(200, 225, 255)');
            var item_id = $(this).attr("data-id");
            $.ajax({
                type: "get",
                url: '/orders/' + item_id + '/user_order',
                success:function(data) {
                    // alert(data);
                }
            });
        });
    });
</script>
<style type="text/css">
    a#u-order{
        display: none;
    }

    a.btn.btn-primary.new-order.pull-right {
        display: none;
    }

    .col-lg-12.breadcrumb-main {
        padding: 0px;
    }
</style>

app/views/orders/my_orders.html.erb
<div class="container">
	<div class="row">
	    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<h3 class="star-heading">
				My Orders
			</h3>
	    </div>
    </div>
	<div class="row">
		<div class="col-lg-12">
			<div class="user-orders">
				<% if @my_orders.blank? %>
					<p class="no-slug">You have no orders.</p>
				<% else %>
					<div class="table-responsive">
			            <table class="table table-striped">
			                <thead>
			                    <tr>
			                    	<th>User name</th>
			                        <th>Item Code</th>
			                        <th>Item Name</th>
			                        <th>Item Specification</th>
			                        <th>Item Price</th>
			                        <th>Qty</th>
			                        <th>Item Delivery Date</th>
			                        <th>Item address</th>
			                        <th>Status</th>
			                    </tr>
			                </thead>

			                <tbody>
		                        <% @my_orders.each do |s| %>
		                            <tr id="element">
		                            	<td><%= s.user.name %></td>
		                                <td><%= s.item.code %></td>
		                                <td><%= s.item.name %></td>
		                                <td><%= s.item.specification %></td>
		                                <td><%= s.item.price %></td>
		                                <td><%= s.item_qty %></td>
		                                <td><%= s.delivery_date.strftime("%d/%m/%Y") %></td>
		                                <td><%= s.delivery_add %></td>
		                                <% if s.is_completed == true %>
		                                	<td>
				                                <P class="panding-status">Confirmed</P>
				                                <%= link_to "View", order_path(s.id), class: "view-order" %>
			                                </td>
		                                <% else %>
			                                <% if s.is_delivered == true %>
			                                	<td>
				                                	<P class="panding-status">Delivered</P>
				                                	<%= link_to "View", order_path(s.id), class: "view-order" %>
				                                </td>
				                            <% else %>
				                                <td>
				                                	<P class="panding-status">Pending</P>
				                                	<%= link_to "View", order_path(s.id), class: "view-order" %>
				                                </td>
			                                <% end %>
		                                <% end %>
		                            </tr>
			                    <% end %>
			                </tbody>
			            </table>
			        </div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/orders/show_order.html.erb
<div class="container">
	<div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h3 class="star-heading">
            Review Order
          </h3>
        </div>
    </div>
	<div class="row">
		<div class="col-lg-12">
			<div class="merch-item">
				<div class="table-responsive">
				<!-- <input type="checkbox" name="vehicle" value="Bike" class="Confirm-order"> 	Confirm order &nbsp;&nbsp;&nbsp;&nbsp; -->
		            <table class="table table-hover">
		                <thead>
		                    <tr>
		                        <th>Item Code</th>
		                        <th>Item Name</th>
		                        <th>Item Specification</th>
		                        <th>Item Price</th>
		                        <th>Item Qty</th>
		                        <th>Item Delivery Date</th>
		                        <th>Sub Total</th>
		                    </tr>
		                </thead>

		                <tbody>
		                	<% i = 0 %>
		                    <% @items.each do |h| %>
	                            <tr>
	                                <td><%= h.code %></td>
	                                <td><%= h.name %></td>
	                                <td><%= h.specification %></td>
	                                <td><%= h.price %></td>
	                                <td><%= @c[i] %></td>
	                                <td><%= (@start_date + h.delivery_days).strftime("%d/%m/%Y") %></td>
	                                <td><%= @c[i].to_i * h.price %></td>
	                            </tr>
	                          	<% i += 1 %>
		                    <% end %>
		                </tbody>
		            </table>
		        </div>
			</div>
			<div class="modify-sec">
				<div class="modify-order">
					<%= link_to "Modify", modify_order_orders_path(type: 'm'), class:"btn btn-primary pull-left"%>
				</div>
				<div class="pay-btn pull-right">
					<%= form_tag make_order_path, :id => 'form' do %>
						<%= submit_tag "Confirm", class: "btn btn-primary submit-order" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>
<style type="text/css">
    a#u-order{
        display: none;
    }

    a.btn.btn-primary.new-order.pull-right {
        display: none;
    }
</style>

<!-- <script type="text/javascript">
    $(document).ready(function(){
        $("#form").submit(function(e) {
	        if($('input[type=checkbox]').is(':checked')){
	            return true;
	        }
		    alert("Please confirm order first!.");
		    return false;
		});
    });
</script> -->

app/views/orders/upload.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 compare-order">
          <h3 class="star-heading">
            Compare and order
          </h3>
        </div>
    </div>
    <div class="row">
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Item Code</th>
                        <th>Item Name</th>
                        <th>Item Price</th>
                        <th>Item Delivery Date</th>
                        <th>Select</th>
                    </tr>
                </thead>

                <tbody>
                        <% i = 0 %>
                        <% @count = 0 %>
                        <% @short_items.each do |h| %>
                            <% h.each do |s| %>
                                <tr id="element" class="item_<%= s.id %>">
                                    <td><%= s.code %></td>
                                    <td><%= s.name %></td>
                                    <td><%= s.price %></td>
                                    <td><%= (@start_date + s.delivery_days).strftime("%d/%m/%Y") %></td>
                                    <td>
                                        <label><input type="radio" class="user_item" id="item_<%= s.id %>" name="<%= s.code %>" data-id="<%= s.id %>-<%= @qty[i]%>-<%= @count %>" data-val="<%= @qty[i] %>"></label>
                                    </td>
                                </tr>
                            <% end %>
                                <tr>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                    <td>&nbsp;</td>
                                </tr>
                                <tr></tr>
                                <% @count += 1 %>
                                <% i += 1 %>
                        <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <%= link_to "Next", show_order_orders_path, class: 'btn btn-primary compare-btn pull-right'%>
        </div>
  </div>
</div>

<script type="text/javascript">
    $(document).ready(function(){

        // $(".user_item").click(function(){
        //     $('.user_item').removeClass("checked");
        //     $(this).addClass("active");
        // });
        $(".user_item").click(function(){
            var dclass = $(this).closest('tr').next('tr').attr("class");
            var pclass = $(this).closest('tr').prev('tr').attr("class");
            var ddclass = $(this).closest('tr').next('tr').next('tr').attr("class");
            var ppclass = $(this).closest('tr').prev('tr').prev('tr').attr("class");
            $('.'+ dclass).css('background-color', 'white');
            $('.'+ pclass).css('background-color', 'white');
            $('.'+ ddclass).css('background-color', 'white');
            $('.'+ ppclass).css('background-color', 'white');
            var a = $(this).attr("id");
            $('.'+ a).css('background-color', 'rgb(200, 225, 255)');
            var item_id = $(this).attr("data-id");
            $.ajax({
                type: "get",
                url: '/orders/' + item_id + '/user_order',
                success:function(data) {
                    // alert(data);
                }
            });
        });
    });
</script>
<style type="text/css">
    a#u-order{
        display: none;
    }

    a.btn.btn-primary.new-order.pull-right {
        display: none;
    }

    .col-lg-12.breadcrumb-main {
        padding: 0px;
    }
</style>

app/views/orders/upload_inventory.html.erb
<%#= form_tag  import_dashboards_path, multipart: true do %>
	<%#= file_field_tag :file %>
	<%#= submit_tag "Import CSV" %>
<%# end %> 