config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  delete "/admin/merchant/:id" => 'admin/merchant#destroy', as: :delete_merchant
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  root to: "dashboards#index"

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    get :my_orders, on: :collection
    get :deliver_order, :on => :member
    get :order_status, :on => :member
  end
  match "make_order", to: "orders#make_order", as: :make_order, via: [:get, :post]

  match '/send_mail', to: 'pages#send_mail', via: 'post'

  resources :dashboards do
    post :import, :on => :collection
    get :upload_inventory, :on => :collection
  end

  resources :items

  resources :pages do
    get :about_us, :on => :collection
    get :faqs, :on => :collection
  end
end

app/views/pages/about_us.html.erb
<h1>This is a about us page.</h1>
<style type="text/css">
	.col-lg-12.breadcrumb-main {
		display: none;
	}
</style>

app/views/pages/faqs.html.erb
<div class="container-content">
  <div class="container">
    <div class="row">
      <div class="main">
        <div>
          <h3 style="font-weight: bold;">FAQs</h3><br/>
          <p>1. How do I place an order?</p>
          <p>2. There’s a missing item in my order, what should I do?</p>
          <p>3. How do I check my order status? </p>
          <p>4. My order was unsuccessful, what should I do?  </p>
        </div>

        <hr/>
        <h3 class="star-heading" style="width: 50%;">Write to us</h3><br/>
        <%= form_tag send_mail_path, class: "contact_form" do %>
          <div class="form-group">
            <%= label_tag 'name', 'Name' %>
            <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Your Name' %>
          </div>
          <div class="form-group">
            <%= label_tag 'email', 'Email' %>
            <%= email_field_tag 'email', nil, class: 'form-control', placeholder: 'Your Email Address' %>
          </div>
          <div class="form-group">
            <%= label_tag 'description', 'Comments' %>
            <%= text_area_tag 'description', nil, class: 'form-control', rows: 4, placeholder: 'Comments...' %>
          </div>
          <%= submit_tag "Send", class: 'btn btn-primary btn-about pull-right' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  form.contact_form {
    width: 50%;
  }

  .col-lg-12.breadcrumb-main {
    display: none;
  }
</style>