config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  delete "/admin/merchant/:id" => 'admin/merchant#destroy', as: :delete_merchant
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  root to: "dashboards#index"

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    get :my_orders, on: :collection
    get :deliver_order, :on => :member
    get :order_status, :on => :member
  end
  match "make_order", to: "orders#make_order", as: :make_order, via: [:get, :post]

  match '/send_mail', to: 'pages#send_mail', via: 'post'

  resources :dashboards do
    post :import, :on => :collection
    get :upload_inventory, :on => :collection
  end

  resources :items

  resources :pages do
    get :about_us, :on => :collection
    get :faqs, :on => :collection
  end
end

app/views/admin/merchant/_index.html.erb
<% if @merchants.present? %>
  <div class="paginated_collection">
    <div class="paginated_collection_contents">
      <div class="index_content">
        <div class="index_as_table">
          <table border="0" cellpadding="0" cellspacing="0" class="index_table index" id="index_table_fields" paginator="true">
            <thead>
              <tr>
                <th class="col col-name">
                  Id
                </th>
                <th class="col col-name">
                  Name
                </th>
                <th class="col col-name">
                  Email
                </th>
                <th class="col col-name">
                  Address
                </th>
                <th class="col col-name">
                  Mobile
                </th>
                <th>&nbsp;</th>
              </tr>
            </thead>
            <tbody>
              <% @merchants.each do |users| %>
                <tr class="odd" id="field_74">
                  <td class="col col-name">
                    <%= users.id %>
                  </td>
                  <td class="col col-name">
                    <%= users.name %>
                  </td>
                  <td class="col col-name">
                    <%= users.email %>
                  </td>
                  <td class="col col-name">
                    <%= users.address %>
                  </td>
                  <td class="col col-name">
                    <%= users.mobile %>
                  </td>
                  <td>
                  	<%= link_to "delete", delete_merchant_path(users.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-delete", role: "button" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <p>Merchant not found</p>
<% end %>