config/routes.rb
  Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  delete "/admin/merchant/:id" => 'admin/merchant#destroy', as: :delete_merchant
  
  devise_for :users, :controllers => { :registrations => "users/registrations" }
  
  root to: "dashboards#index"

  resources :orders do
    post :upload, :on => :collection
    get :user_order, :on => :member
    get :show_order, :on => :collection
    get :modify_order, on: :collection
    get :my_orders, on: :collection
    get :deliver_order, :on => :member
    get :order_status, :on => :member
  end
  match "make_order", to: "orders#make_order", as: :make_order, via: [:get, :post]

  match '/send_mail', to: 'pages#send_mail', via: 'post'

  resources :dashboards do
    post :import, :on => :collection
    get :upload_inventory, :on => :collection
  end

  resources :items

  resources :pages do
    get :about_us, :on => :collection
    get :faqs, :on => :collection
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" style="overflow: visible;">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shop" %></title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>
  <!-- container section start -->
  <section id="container" class="">
    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
      </div>

      <!--logo start-->
      <div class="site-logo">
        <%= link_to "/", class: "logo" do %>
          <span class="lite">Howzie</span>
        <% end %>
      </div>
      <!--logo end-->

      <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">
          <!-- user login dropdown start-->
          <% if user_signed_in? %>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="username"><%= current_user.name %></span>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li class="eborder-top">
                  <%= link_to edit_user_registration_path do %>
                    <i class="icon_profile"></i> My Profile
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, :method => :delete do %>
                    <i class="icon_key_alt"></i> Log Out
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
    <aside>
      <div id="sidebar" class="nav-collapse ">
        <!-- sidebar menu start-->
        <ul class="sidebar-menu">
          <li class="about-main">
            <%= link_to about_us_pages_path, class: "about_us main-layout-about-us" do %>
              About
            <% end %>
          </li>
          <li class="faq-main">
            <%= link_to faqs_pages_path, class: "faqs main-layout-faq" do %>
              Help
            <% end %>
          </li>
        </ul>
        <!-- sidebar menu end-->
      </div>
    </aside>
    <!--sidebar end-->

    <!--main content start-->
    <section id="main-content">
      <section class="wrapper">
        <!--overview start-->
        <% if user_signed_in? %>
          <div class="container">
            <div class="row">
              <div class="col-lg-12 breadcrumb-main">
                <ol class="breadcrumb">
                  <li>
                    <% if current_user.user_type == true %>
                      <p class="breadcrumb-name">Merchant id: <span class="customer-id"><%= current_user.id %></span></p>
                    <% else %>
                      <p class="breadcrumb-name">Customer id: <span class="customer-id"><%= current_user.id %></span></p>
                    <% end %>
                  </li>
                  <% if current_user.user_type == true %>
                    <%= link_to "Your Orders", my_orders_orders_path, class: 'btn btn-primary new-order merchant-order' %>
                    <%= link_to "Upload Inventory", upload_inventory_dashboards_path, class: 'btn btn-primary new-order pull-right merchant-action' %>
                  <% else %>
                    <%= link_to 'New Order', orders_path, class: 'btn btn-primary new-order pull-right' %>
                  <% end %>
                </ol>
              </div>
            </div>
          </div>
          <% end %>
          <div class="container notif_container">
            <div class="row">
              <div class="col-lg-12">
                <%= bootstrap_flash %>
              </div>
            </div>
          </div>
          <%= yield %>
      </section>
    </section>
  </section>

  <!-- javascripts -->
  <!-- <script src="assets/js/jquery.js"></script>
  <script src="assets/js/jquery-ui-1.10.4.min.js"></script>
  <script src="assets/js/jquery-1.8.3.min.js"></script>
  <script type="text/javascript" src="assets/js/jquery-ui-1.9.2.custom.min.js"></script>
  <!-- bootstrap -->
  <!-- <script src="/assets/bootstrap.min.js"></script> -->
  
  <!--custome script for all page-->
  <script src="/assets/scripts.js"></script>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en" style="overflow: visible;">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shop" %></title>
    <%= csrf_meta_tags %>

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>
  <!-- container section start -->
    <header class="header dark-bg">
      <div class="toggle-nav">
        <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"></i></div>
      </div>

      <!--logo start-->
      <%= link_to "/", class: "logo" do %>
        <span class="lite">Howzie</span>
      <% end %>
      <!--logo end-->
      <div class="top-nav notification-row">
        <!-- notificatoin dropdown start-->
        <ul class="nav pull-right top-menu">
          <!-- user login dropdown start-->
          <% if user_signed_in? %>
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="username"><%= current_user.name %></span>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li class="eborder-top">
                  <%= link_to edit_user_registration_path do %>
                    <i class="icon_profile"></i> My Profile
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, :method => :delete do %>
                    <i class="icon_key_alt"></i> Log Out
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <!-- user login dropdown end -->
        </ul>
        <!-- notificatoin dropdown end-->
      </div>
    </header>
    <!--header end-->

    <!--sidebar start-->
      <div id="authsidebar" class="nav-collapse auth-sidebar">
        <div class="logo-slug">
          <p class="howzie-logo">Howzie</p>
          <p class="howzie-slug">Makes ordering easy</p>
        </div>
        <!-- sidebar menu start-->
        <div class="qwery">
        <ul class="sidebar-menu">
          <li class="about-main">
            <%= link_to about_us_pages_path, class: "about_us" do %>
              About
            <% end %>
          </li>
          <li class="faq-main">
            <%= link_to faqs_pages_path, class: "faqs" do %>
              Faq
            <% end %>
          </li>
        </ul>
        </div>
        <!-- sidebar menu end-->
      </div>

      <div class="wrapper auth-sidebar">
          <%= bootstrap_flash %>
          <%= yield %>
      </div>
  
  <!--custome script for all page-->
  <script src="/assets/scripts.js"></script>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shop" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top landing-nav">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- <a class="navbar-brand" href="#">Shop</a> -->
        <%= link_to image_tag("logo.png", :class => "img_preview"), "/", class: "navbar-brand logo" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if current_user.user_type == true %>
                <li><%= link_to "Your Orders", my_orders_orders_path, class: 'merchant-order' %></li>
                <li><%= link_to "Upload Inventory", upload_inventory_dashboards_path, class: 'merchant-order' %></li>
                <li><%= link_to " (Merchant) #{current_user.name}", edit_user_registration_path, class:"fa fa-user" %></li>
              <% else %>
                <li><%= link_to 'New Order', orders_path, class: 'new-order', id: 'u-order' %></li>
                <li><%= link_to " (Buyer) #{current_user.name}", edit_user_registration_path, class:"fa fa-user" %></li>
              <% end %>
              <li><%= link_to "  Sign out", destroy_user_session_path, :method => :delete, class:"fa fa-sign-out" %></li>
            <% else %>
              <li id="login"><%= link_to "  Sign In", new_user_session_path, class:"fa fa-sign-in" %> </li>
              <li id="logout"><%= link_to "  Sign up", new_user_registration_path, class:"fa fa-sign-up" %> </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <div class="sticky-footer">
            <%= yield %>
          </div>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->
  </body>
  <footer class="footer-distributed">
    <div class="footer-left">
      <p class="footer-company-name">ShopIndeed &copy; 2017</p>
    </div>
  </footer>
<script type="text/javascript">
  $(document).ready(function() {
    function setHeight() {
      windowHeight = $(window).innerHeight();
      $('.sticky-footer').css('min-height', windowHeight-127);
    };
    setHeight();
    
    $(window).resize(function() {
      setHeight();
    });
  });
</script>
</html>